# Generated by Django 3.2.3 on 2026-03-26 13:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cats', '0003_shelter'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='capacity',
            field=models.PositiveIntegerField(default=50, help_text='Максимальное количество котов в приюте.'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_shelters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Номер телефона должен содержать от 7 до 15 цифр и может начинаться с «+».', regex='^\\+?\\d{7,15}$')]),
        ),
        migrations.CreateModel(
            name='ShelterEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('moderator', 'Модератор'), ('employee', 'Сотрудник')], default='employee', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='cats.shelter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelter_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='shelteremployee',
            constraint=models.UniqueConstraint(fields=('shelter', 'user'), name='unique_shelter_employee'),
        ),
    ]
